version: '3.7'
services:

  symfony:
    container_name: rabbitmq_symfony
    build:
      context: .docker/symfony
      args:
        TIMEZONE: 'Europe/Paris'
    volumes:
      - ./:/var/www/symfony
    networks:
      - symfony

  nginx:
    container_name: rabbitmq_nginx
    build:
      context: .docker/nginx
    volumes:
      - ./:/var/www/symfony
    env_file:
      - .docker/.env.nginx
    ports:
      - 8011:80
    networks:
      - symfony

  mailer:
    container_name: rabbitmq_mailcatcher
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
    networks:
      - symfony

  rabbitmq:
    container_name: rabbitmq_rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - symfony

networks:
  symfony: